### ISSUE TITLE
Questions about the result

### ISSUE THREAD

**Issue by ghost** [andreamad8/Universal-Transformer-Pytorch#3]
Very glad to find this codes. I'm a little confused the output result. Is the output acc the accuracy or the error rate? According to the code, it seems to be accuracy. But if so, the accuracy is too small as I got the output acc as almost 0. Could you please help me to address the problem?

**Comment by andreamad8** [comment]
Hi, 

the output is accuracy. I just manually report the error rate to compare it to existing transformer results. 
As you can notice still some tasks doesn't work as well as the original code. If you can spot any mistake in the code pls let me know. 

Best 

Andrea
