### ISSUE TITLE
encoder-decoder problem

### ISSUE THREAD

**Issue by ZTurboX** [andreamad8/Universal-Transformer-Pytorch#4]
![image](https://user-images.githubusercontent.com/5669444/51176179-3bc0f180-18f7-11e9-97ff-063e7fdd7f86.png)

in forward function,why only has encoder without decoder?

**Comment by andreamad8** [comment]
Hi, 

so basically babi data is one step decoding, so it doesn't require a decoder.  I had the same doubt before, so asked directly to the authors, check the previous issue:  https://github.com/MostafaDehghani/bAbI-T2T/issues/4 

So basically the output of the encoder, a set of embedding, is averaged to make the final prediction. No decoder needed. 

I hope this help 

Best 

Andrea

**Comment by ZTurboX** [comment]
thanks a lot

Andrea Madotto <notifications@github.com> 于2019年1月16日周三 下午9:18写道：
